# Generated by Django 5.1.2 on 2024-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0002_alter_book_author_alter_book_status_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='количество страниц'),
            preserve_default=False,
        ),
    ]
