# Generated by Django 5.1.2 on 2024-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0004_book_sbin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sbin',
            field=models.CharField(max_length=12, verbose_name='(SBIN) уникальный номер'),
        ),
    ]
