# Generated by Django 5.1.2 on 2024-10-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0005_alter_book_sbin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'объявление', 'verbose_name_plural': 'объявления'},
        ),
    ]
