# Generated by Django 5.1.2 on 2024-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0006_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='кол. страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sbin',
            field=models.CharField(max_length=20, verbose_name='SBIN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='наличие книги'),
        ),
    ]
