# Generated by Django 5.1.2 on 2024-11-03 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0007_author_alter_book_options_alter_book_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ex_app.author', verbose_name='автор книги'),
        ),
    ]
