# Generated by Django 5.1.2 on 2024-11-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0008_book_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
