# Generated by Django 5.1.2 on 2024-11-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex_app', '0009_remove_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author2',
            new_name='author',
        ),
    ]
